name: Radar Mercado IA

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  radar:
    runs-on: ubuntu-latest

    steps:
      - name: Teste Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.CHAT_ID }}" \
          -d text="✅ Radar Mercado IA online e funcionando!"

# teste
